### ISSUE TITLE
Update plugin

### ISSUE THREAD

**Issue by st33vil** [CollaboraOnline/collabora-mattermost#10]
Hi,

  it would be useful if you could update plugin so that includes recent changes (there were nine commits after initial release).
Thanks!

**Comment by MozzieAU** [comment]
Ditto. 
Please update the plugin and submit it to Mattermost for inclusion in the plugin marketplace.
PS Im happy to contribute a bounty to get this done guys.
Regards
Ray

**Comment by MozzieAU** [comment]
BUMP. 
Really folks it would be appreciated if a new release could be compiled. 
We cannot get the existing release to work due to issues noted under bug and are not eqqiped to compile it ourselves. 
Happy to pay a bounty as I said above. Can you help @florin-ciornei ?

**Comment by wget** [comment]
@MozzieAU I have just had received access to this repo a few days ago :) A bunch of changes will be merged shortly wrt. this plugin :) Please be patient :) We work hard on [improving things up](https://developers.mattermost.com/extend/plugins/community-plugin-marketplace/) :)

**Comment by timar** [comment]
We released 1.1.0 today.
