### ISSUE TITLE
Collabora frame does not resize when Mattermost window is resized

### ISSUE THREAD

**Issue by adsche** [CollaboraOnline/collabora-mattermost#22]
Hi all,

a little UX feature request I guess:

I usually keep my Mattermost window rather narrow. That's good enough for chat but when clicking 'edit' on a document, I would want to have a larger window. However, if I resize the window after opening Collabora, the Collabora frame stays narrow. I have to close it and re-open it to achieve what I wanted.

It seems that this should be fixable by applying some relative styling to the frame?

Mattermost 4.6 on macOS, Collabora Mattermost 1.1.0, CODE, LOOLWSD 6.4.0, LOKit 6.4-10

**Comment by chetanyakan** [comment]
This is fixed on the latest master.
