### ISSUE TITLE
Feature request: Remember sidebar state or allow to hide sidebar by default

### ISSUE THREAD

**Issue by adsche** [CollaboraOnline/collabora-mattermost#25]
I rarely need the sidebar for the type of quick copy-editing we do via mattermost, but it takes a lot of space and usually causes the page to be displayed smaller than it could be. I'd love to hide the sidebar by default.

Since this is a user preference, it would also be amazing if the plugin could remember a user's sidebar state from the last open collabora frame.

Cheers!

**Comment by chetanyakan** [comment]
@adsche If you are talking about the Collabora sidebar, it is not controlled by this plugin.

You can check the changes in collabora suggested here for reference: https://help.nextcloud.com/t/initial-setting-of-the-display-state-of-the-sidebar/71541
