### ISSUE TITLE
Avoid security risk with a fallback password

### ISSUE THREAD

**Issue by lieut-data** [CollaboraOnline/collabora-mattermost#5]
The current code uses a fallback password in the event it cannot write a key to the key value store on startup, or if it cannot read the key during regular operations, e.g.:
https://github.com/CollaboraOnline/collabora-mattermost/blob/3701315f318254c7fe37645e796ef1013f8f1a74/server/token.go#L51-L55

This is a potential security hole. I'd suggest failing the `OnActivate` altogether if the write fails, and then just caching the key in memory thereafter, eliminating the need for a fallback password altogether.

**Comment by florin-ciornei** [comment]
Hi @lieut-data ! By caching the key in memory, do you mean having a simple variable that will store the password?

**Comment by lieut-data** [comment]
@florin-ciornei, that would be the idea, yes, if you want to avoid having to worry about future `KVGet` errors and what to do in that case.
