### ISSUE TITLE
BUG - After upgrade to Mattermost 6.0 Collabora windows cannot be closed anymore

### ISSUE THREAD

**Issue by jprusch** [CollaboraOnline/collabora-mattermost#53]
**Summary**

Opening a file with Collabora on Mattermost 6.0 with the desktop 5.0 app doesn't display the close button anymore (Out of screen)

**Steps To Reproduce**

1. Upgrade your Mattermost server to 6.0
2. Open a file with Collabora
3. Try to close the window

**Expected behavior**

A close button is displayed

**Observed Behavior (that appears unintentional)**

Close button is not shown

**Screenshots**

![image](https://user-images.githubusercontent.com/9337414/137145537-d7e0c477-998b-4992-b7c6-5b794f93e89b.png)

**Environment**
-  Mattermost version: 6.0
-  OS: Windows 10
-  Platform: browser, desktop app
-  Browser (if applicable): e.g. chrome
-  Platform Version: e.g. chrome 94.x, desktop 5.0

There seems to be a fix already in the solved issues, but I'm not 100% sure, as I cannot build a new plugin version from master.

**Comment by kiroswu** [comment]
+1. Does this plugin still maintain? Facing same issue

**Comment by jprusch** [comment]
Is working now. Might have been a Mattermost bug.
