### ISSUE TITLE
MATTERMOST_SERVER_URL may not support subpaths

### ISSUE THREAD

**Issue by lieut-data** [CollaboraOnline/collabora-mattermost#7]
Some Mattermost installations run at a subpath instead of at the root of domain, e.g. `http://example.com/mattermost/team/channel`.

The current strategy to replace `MATTERMOST_SERVER_URL` in the payload sent down from the plugin may not support subpaths correctly:
https://github.com/CollaboraOnline/collabora-mattermost/blob/3701315f318254c7fe37645e796ef1013f8f1a74/webapp/src/rootModal.jsx#L23-L34

Consider querying the `SiteURL` from the configuration exposed via Redux instead. It may also be possible to eliminate the `MATTERMOST_SERVER_URL` sent down by the plugin and just send it down with the configured `SiteURL` directly.

**Comment by florin-ciornei** [comment]
Hi @lieut-data ! May I ask for more details about the `SiteURL`? As I understand, I can somehow also access it on the server-side of the plugin, but I cannot find how.

**Comment by lieut-data** [comment]
@florin-ciornei and I synched up offline, but for posterity: you can access the configured `SiteURL` via the `GetConfig` API method, and accessing `ServiceSettings.SiteURL`.
