### ISSUE TITLE
Document not loading with mattermost when alias_groups defined

### ISSUE THREAD

**Issue by gstlouisgit** [CollaboraOnline/collabora-mattermost#72]
I have been trying to get Collabora online working in a web application following a similar setup as described [here](https://github.com/CollaboraOnline/collabora-online-sdk-examples/tree/master/webapp/php).  I always get 404 not found or 403 forbidden when using alias_groups

Mattermost with the collabora plugin works without need of any configuration in coolwsd.xml.  In the link above, the example does not mention you need to mess around with alias_groups in coolwsd, but I've been trying anything. 

I've configured alias_groups with `<host desc="hostname to allow or deny." allow="true">http://domain.ca</host>` trying to get my testing url to open a document.  When I do this mattermost crashes.

What is the point of alias_groups?  I added my mattermost url and it still just crashes everything, and I've never been able to get collabora to work in my web application.  

I would like to understand how mattermost gets Collabora working without using this alias_groups stuff.  Yet I can't get anything going inside a web application.  Any advice or clarification would be appreciated.

**Comment by jprusch** [comment]
We run our CODE server w/o docker with an nginx proxy handling tls/ssl.

You might want to try:
`
<storage desc="Backend storage">
        <filesystem allow="false"/>
        <wopi allow="true" desc="Allow/deny wopi storage.">
                <host allow="true" desc="Regex pattern of hostname to allow or deny.">our\.domain\.org</host>
                <host allow="true" desc="Regex pattern of hostname to allow or deny.">192\.168\.2\.88</host>
                <host allow="true" desc="Regex pattern of hostname to allow or deny.">localhost</host>
                <host allow="true" desc="Regex pattern of hostname to allow or deny.">10\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}</host>
                <host allow="true" desc="Regex pattern of hostname to allow or deny.">172\.1[6789]\.[0-9]{1,3}\.[0-9]{1,3}</host>
                <host allow="true" desc="Regex pattern of hostname to allow or deny.">172\.2[0-9]\.[0-9]{1,3}\.[0-9]{1,3}</host>
                <host allow="true" desc="Regex pattern of hostname to allow or deny.">172\.3[01]\.[0-9]{1,3}\.[0-9]{1,3}</host>
                <host allow="true" desc="Regex pattern of hostname to allow or deny.">192\.168\.[0-9]{1,3}\.[0-9]{1,3}</host>
                <host allow="false" desc="Regex pattern of hostname to allow or deny.">192\.168\.1\.1</host>
                <max_file_size desc="Maximum document size in bytes to load. 0 for unlimited." type="uint">0</max_file_size>
                <locking desc="Locking settings">
                        <refresh default="900" desc="How frequently we should re-acquire a lock with the storage server, in seconds (default 15 mins) or 0 for no refresh" type="int">900</refresh>
                </locking>
        </wopi>
        <ssl desc="SSL settings">
                <as_scheme default="true" desc="When set we exclusively use the WOPI URI's scheme to enable SSL for storage" type="bool">true</as_scheme>
                <enable desc="If as_scheme is false or not set, this can be set to force SSL encryption between storage and coolwsd. When empty this defaults to following the ssl.enabled"/>
                <cert_file_path desc="Path to the cert file" relative="false"/>
                <key_file_path desc="Path to the key file" relative="false"/>
                <ca_file_path desc="Path to the ca file. If this is not empty, then SSL verification will be strict, otherwise cert of storage (WOPI-like host) will not be verified." relative="false"/>
                <cipher_list desc="List of OpenSSL ciphers to accept. If empty the defaults are used. These can be overridden only if absolutely needed."/>
        </ssl>
</storage>
`

**Comment by gstlouisgit** [comment]
Hi. thanks for the reply. 
I run CODE server on a virtual machine, so without docker.

I added the `<host allow` string I didn't have, and say my domain is domain.ca I added 
<host allow="true" desc="Regex pattern of hostname to allow or deny.">domain\.ca</host>

same for mattermost

You didn't share your <alias_groups, but mine is set to groups ex:

`<alias_groups desc="default mode is 'first' it allows only the first host when groups are not defined. set mode to 'groups' and define group to allow multiple host and its aliases" mode="groups">
                <group>
                <host desc="hostname to allow or deny." allow="true">https://domain.ca:443</host>
                                <host desc="hostname to allow or deny." allow="true">https://sub.mattermosturl.ca:443</host>
                                </group></alias_groups>`
                                
When I set alias_groups to "groups" and restart coolwsd, mattermost stops working and journalctl -ucoolwsd says "No acceptable WOPI hosts found matching the target host" 

but my custom app gives a different error ERR  WOPI::CheckFileInfo failed for URI [https://domain.ca/wopi/files/1?access_token=test&access_token_ttl=0]: 403 Forbidden

so nothing works, mattermost no longer works, but if I set it back to alias_groups to "first" mattermost works and shows the document

I do not know what I am doing wrong.  my head is spinning...

**Comment by jprusch** [comment]
Did you try with IP addresses instead of fqdns? I added our Mattermost server with domain and IP. You can also enable some ip ranges for testing. Are you running a reverse proxy in front of the CODE server? Who is terminating TLS/SSL?

```
<storage desc="Backend storage">
<filesystem allow="false"/>
<wopi allow="true" desc="Allow/deny wopi storage.">
    <host allow="true" desc="Regex pattern of hostname to allow or deny.">our\.domain\.org</host> 
    <host allow="true" desc="Regex pattern of hostname to allow or deny.">192\.168\.2\.88</host> 
    <host allow="true" desc="Regex pattern of hostname to allow or deny.">localhost</host> 
    <host allow="true" desc="Regex pattern of hostname to allow or deny.">10\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}</host> 
    <host allow="true" desc="Regex pattern of hostname to allow or deny.">172\.1[6789]\.[0-9]{1,3}\.[0-9]{1,3}</host> 
    <host allow="true" desc="Regex pattern of hostname to allow or deny.">172\.2[0-9]\.[0-9]{1,3}\.[0-9]{1,3}</host> 
    <host allow="true" desc="Regex pattern of hostname to allow or deny.">172\.3[01]\.[0-9]{1,3}\.[0-9]{1,3}</host>
    <host allow="true" desc="Regex pattern of hostname to allow or deny.">192\.168\.[0-9]{1,3}\.[0-9]{1,3}</host>
    <host allow="false" desc="Regex pattern of hostname to allow or deny.">192\.168\.1\.1</host>
    <max_file_size desc="Maximum document size in bytes to load. 0 for unlimited." type="uint">0</max_file_size>
    <locking desc="Locking settings"
         <refresh default="900" desc="How frequently we should re-acquire a lock with the storage server, in seconds (default 15 mins) or 0 for no refresh" type="int">900</refresh> 
    </locking>
</wopi>

<ssl desc="SSL settings">
    <as_scheme default="true" desc="When set we exclusively use the WOPI URI's scheme to enable SSL for storage" type="bool">true</as_scheme>
    <enable desc="If as_scheme is false or not set, this can be set to force SSL encryption between storage and coolwsd. When empty this defaults to following the ssl.enabled"/>
    <cert_file_path desc="Path to the cert file" relative="false"/>
    <key_file_path desc="Path to the key file" relative="false"/> 
    <ca_file_path desc="Path to the ca file. If this is not empty, then SSL verification will be strict, otherwise cert of storage (WOPI-like host) will not be verified." relative="false"/> 
    <cipher_list desc="List of OpenSSL ciphers to accept. If empty the defaults are used. These can be overridden only if absolutely needed."/>
    </ssl>
</storage>
```

**Comment by gstlouisgit** [comment]
ya this did not make a difference

In your setup, do you have mode "groups" in you alias_groups ?  Or is it setup as "first"?

**Comment by jprusch** [comment]
I still have no idea what's your issue with alias groups is. I don't use them.
And I appreciate when you answer my questions...

**Comment by gstlouisgit** [comment]
I have multiple wopi locations.  There is the default one with mattermost.  This works out of the box.  But if you want to setup a second location, like I am with another domain to have a custom app.  You can't just setup <host allow=* tags, you need to enable alias_groups to "groups".  This is what I have read and understood, this is what the error logs always complain about.
 
Now, I finally got my custom app working, this is by setting up the:
`<host allow="true" desc="Regex pattern of hostname to allow or deny.">domain\.org</host> // custom app
<host allow="true" desc="Regex pattern of hostname to allow or deny.">sub\.mattermost\.org</host>//mattermost  `

Doing this, domain.org works ( since it is first ), and I can get the document to open, however, it will now complain and say:
`ERR  Only allowed host is: sub.domain.org ( mattermost ), To use multiple host/aliases check alias_groups tag in configuration| wsd/HostUtil.cpp:224`

Do you understand now about alias_groups ?

So, I go into the coolwsd.xml file and switch alias_groups mode to "groups", again my custom app works, but now mattermost again does not work because it is now complaining about:

`Unauthorized Request while starting session on https://sub.domain.org:443/plugins/com.collaboraonline.mattermost/wopi/files/ebf5a11df7bm5j4187r9f9fcpc for socket #30. Terminating connection. Error: No acceptable WOPI hosts found matching the target host [sub.domain.org] in config.| wsd/COOLWSD.cpp:4862`

So now I am trying to figure out how to get coolwsd to let mattermost open its wopi request.

I don't know what you're talking about for ssl.  My ssl it properly setup using let's encrypt and none of these errors have to do with secure socket requests.

**Comment by gstlouisgit** [comment]
ok 
I have found my mistake.  In the coolwsd.xml doc, it does not provide much examples if adding several group tags, so I was adding several hosts to one group, when you need to add 1 host per group

These tags below fixed the problem with `alias_groups` mode "groups"

```
<group>
        <host allow="true" desc="hostname to allow or deny.">https://domain.org</host>
</group>
<group>
        <host allow="true" desc="hostname to allow or deny.">http://sub.mattermost.org</host>
</group>
```

**Comment by leandrocombr** [comment]
How do I resolve this error?

```
wsd-30555-30596 2023-03-10 14:24:35.138252 -0400 [ docbroker_002 ] ERR  loading document exception: Access denied. WOPI::CheckFileInfo failed on: https://url.net
wsd-30555-30596 2023-03-10 14:24:35.138274 -0400 [ docbroker_002 ] ERR  Failed to add session to [https://url.net:443/aee.txt] w
wsd-30555-30596 2023-03-10 14:24:35.138294 -0400 [ docbroker_002 ] ERR  Unauthorized Request while starting session on https://url.net
wsd-30555-30596 2023-03-10 14:24:35.140439 -0400 [ docbroker_002 ] ERR  #31: Read failed, have 0 buffered bytes (ECONNRESET: Connection reset by peer)| net/S
wsd-30555-30596 2023-03-10 14:24:35.140476 -0400 [ docbroker_002 ] WRN  Unassociated Kit (30580) disconnected unexpectedly| wsd/COOLWSD.cpp:3405
/usr/bin/coolmount: mount failed remount [/opt/cool/child-roots/xCRJWIvkz0Z6vz8J] readonly: Operation not permitted.
kit-30597-30561 2023-03-10 14:24:35.151298 -0400 [ kit_spare_003 ] ERR  Failed to mount [/opt/cool/systemplate] -> [/opt/cool/child-roots/xCRJWIvkz0Z6vz8J/]
kit-30597-30561 2023-03-10 14:24:35.151367 -0400 [ kit_spare_003 ] ERR  Failed to mount [/opt/cool/systemplate] -> [/opt/cool/child-roots/xCRJWIvkz0Z6vz8J/],
```

**Comment by gstlouisgit** [comment]
that can be so many things.  You are better off starting a new thread describing your environment and how you set things up.
